# This file is a template, and migh
image: gcc

build:
  stage: build
  before_script:
    - sed -i 's/deb\.debian\.org/mirrors\.ustc\.edu\.cn/g' /etc/apt/sources.list && sed -i 's/security\.debian\.org/mirrors\.ustc\.edu\.cn/g' /etc/apt/sources.list
    - apt update && apt -y install make autoconf cmake
  script:
    - cmake .
    - make
  artifacts:
    paths:
      - "build/*"
